Optional scheduling tests
SabrinaSnider/my-portfolio pull request #16
Opened 2020-06-16 20:15 UTC by SabrinaSnider

Wrote 5 new tests for the feature of adding optional attendees to meeting requests. The scenarios for the tests are:

1. Add an optional attendee who has an all-day event to the meeting request. The optional attendee should be ignored in this scenario since they cannot make any meeting time.
2. Add an optional attendee who has an event, but is available for the meeting at other times. Meeting times including the optional attendee should be returned.
3. Add an optional attendee who has an event, but whose schedule still can't fit any of the available meeting times. The optional attendee should be ignored in this scenario since they cannot make any meeting time.
4. Make no mandatory attendees, but have two optional attendees with several gaps in their schedules. Those gaps should be identified and returned.
5. Make no mandatory attendees, but have two optional attendees with no gaps in their schedules. The query should return that no time is available.

2020-06-16 21:31 UTC, brucezheng requested changes
Can you add a test with meetings that overlap? E.g.

* Meeting 1: [8:15, 9:00, Person A]
* Meeting 2: [8:45, 9:30, Person B]

2020-06-16 21:31 UTC, brucezheng commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +        Arrays.asList(TimeRange.fromStartEnd(TimeRange.START_OF_DAY, TIME_0800AM, false),
Add a line break between the opening parenthesis and the first function argument. Same below.

2020-06-17 18:20 UTC, brucezheng approved these changes

2020-06-17 22:40 UTC, ccyang314 approved these changes

2020-06-18 17:21 UTC, merged